
version: '3.7'

services:

  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - './app:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - woo_os

  wordpress:
    container_name: woopress
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app:/bitnami'
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=password
      - WORDPRESS_BLOG_NAME=WooPress Demo
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - woo_os

networks:
  woo_os:

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local